### ISSUE TITLE
[QUESTION] - Fleet adapter implementation

### ISSUE THREAD

**Issue by cwrx777** [open-rmf/rmf_ros2#184]
Hi,

Consider the scenario where there are 3fleets of MiR100 robots. 
Fleet 1, [the MiR100 is used for transporting carts.](https://www.youtube.com/watch?v=u4KMbZZFYTI)  This involves actions such as pick up cart and drop off cart.
Fleet 2, [the MiR100 is mounted with e.g. a shelf/smart cabinet.](https://www.youtube.com/watch?v=j70H23YAwfo). 
Fleet 3, [the MIR100 is mounted with UV light.](https://www.youtube.com/watch?v=gTbdJ9g4nNc) it will just be going rounds based on a predefined path, including e.g. turn on/off light. 

Should all fleets be using the same fleet adapter? where should the logic of the actions be implemented?

**Comment by mxgrey** [comment]
You can manage them all with a single fleet adapter executable, but if they perform different tasks then you should call [`add_fleet(...)`](https://github.com/open-rmf/rmf_ros2/blob/2cee31f31bc8f8cb6627f03278ee35cd1332c182/rmf_fleet_adapter/include/rmf_fleet_adapter/agv/Adapter.hpp#L81-L104) once for each (so a total of three times). One assumption that the `rmf_fleet_adapter` library makes is that all robots in a single "fleet" (defined by the object that gets returned by `Adapter::add_fleet`) are all able to perform the same types of tasks.

If you have custom actions for the robots to perform (e.g. sanitizing), then I recommend using the `perform_action` feature described [here](https://github.com/open-rmf/rmf/discussions/140#discussioncomment-2235146).

Since this is not an issue report, I'm going to close the ticket. For general discussions that aren't bug reports or formal feature requests, we encourage everyone to use the [RMF Discussions](https://github.com/open-rmf/rmf/discussions) page.
